spring.application.name=backend
# Configuração do Servidor
server.port=3001

# Chave da API do Google Gemini (Defina nas variáveis de ambiente do sistema ou aqui para teste)
#gemini.api.key=${GEMINI_API_KEY}
gemini.api.key=AIzaSyB-6W1NV04LNZWMu_KN4gNwW-9rUTuFiQk

# Configurações opcionais de Log
logging.level.org.springframework.web=INFO

# Configurações do Servidor de E-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sachabm@gmail.com
spring.mail.password=luir fygx syvq ldmm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# --- CONFIGURAÇÃO DE EMAIL (HOSTINGER) ---
# spring.mail.host=smtp.hostinger.com
# spring.mail.port=587

# 1. Seu email completo da Hostinger
# spring.mail.username=contato@valorprecatorio.adv.br

# 2. A senha REAL que você usa para entrar nesse email (no webmail da Hostinger)
# spring.mail.password=SUA_SENHA_DO_EMAIL_AQUI

# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true